// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/seva/animevista/ent/anime"
	"github.com/seva/animevista/ent/predicate"
)

// AnimeUpdate is the builder for updating Anime entities.
type AnimeUpdate struct {
	config
	hooks    []Hook
	mutation *AnimeMutation
}

// Where appends a list predicates to the AnimeUpdate builder.
func (_u *AnimeUpdate) Where(ps ...predicate.Anime) *AnimeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAverageRating sets the "average_rating" field.
func (_u *AnimeUpdate) SetAverageRating(v float64) *AnimeUpdate {
	_u.mutation.ResetAverageRating()
	_u.mutation.SetAverageRating(v)
	return _u
}

// SetNillableAverageRating sets the "average_rating" field if the given value is not nil.
func (_u *AnimeUpdate) SetNillableAverageRating(v *float64) *AnimeUpdate {
	if v != nil {
		_u.SetAverageRating(*v)
	}
	return _u
}

// AddAverageRating adds value to the "average_rating" field.
func (_u *AnimeUpdate) AddAverageRating(v float64) *AnimeUpdate {
	_u.mutation.AddAverageRating(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AnimeUpdate) SetUpdatedAt(v time.Time) *AnimeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AnimeMutation object of the builder.
func (_u *AnimeUpdate) Mutation() *AnimeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnimeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnimeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnimeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnimeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AnimeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := anime.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AnimeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(anime.Table, anime.Columns, sqlgraph.NewFieldSpec(anime.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AverageRating(); ok {
		_spec.SetField(anime.FieldAverageRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAverageRating(); ok {
		_spec.AddField(anime.FieldAverageRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(anime.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{anime.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnimeUpdateOne is the builder for updating a single Anime entity.
type AnimeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnimeMutation
}

// SetAverageRating sets the "average_rating" field.
func (_u *AnimeUpdateOne) SetAverageRating(v float64) *AnimeUpdateOne {
	_u.mutation.ResetAverageRating()
	_u.mutation.SetAverageRating(v)
	return _u
}

// SetNillableAverageRating sets the "average_rating" field if the given value is not nil.
func (_u *AnimeUpdateOne) SetNillableAverageRating(v *float64) *AnimeUpdateOne {
	if v != nil {
		_u.SetAverageRating(*v)
	}
	return _u
}

// AddAverageRating adds value to the "average_rating" field.
func (_u *AnimeUpdateOne) AddAverageRating(v float64) *AnimeUpdateOne {
	_u.mutation.AddAverageRating(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AnimeUpdateOne) SetUpdatedAt(v time.Time) *AnimeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AnimeMutation object of the builder.
func (_u *AnimeUpdateOne) Mutation() *AnimeMutation {
	return _u.mutation
}

// Where appends a list predicates to the AnimeUpdate builder.
func (_u *AnimeUpdateOne) Where(ps ...predicate.Anime) *AnimeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnimeUpdateOne) Select(field string, fields ...string) *AnimeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Anime entity.
func (_u *AnimeUpdateOne) Save(ctx context.Context) (*Anime, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnimeUpdateOne) SaveX(ctx context.Context) *Anime {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnimeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnimeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AnimeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := anime.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AnimeUpdateOne) sqlSave(ctx context.Context) (_node *Anime, err error) {
	_spec := sqlgraph.NewUpdateSpec(anime.Table, anime.Columns, sqlgraph.NewFieldSpec(anime.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Anime.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, anime.FieldID)
		for _, f := range fields {
			if !anime.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != anime.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AverageRating(); ok {
		_spec.SetField(anime.FieldAverageRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAverageRating(); ok {
		_spec.AddField(anime.FieldAverageRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(anime.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Anime{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{anime.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
