// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/seva/animevista/ent/anime"
	"github.com/seva/animevista/ent/predicate"
	"github.com/seva/animevista/ent/userrating"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAnime      = "Anime"
	TypeUserRating = "UserRating"
)

// AnimeMutation represents an operation that mutates the Anime nodes in the graph.
type AnimeMutation struct {
	config
	op                Op
	typ               string
	id                *int64
	average_rating    *float64
	addaverage_rating *float64
	updated_at        *time.Time
	clearedFields     map[string]struct{}
	done              bool
	oldValue          func(context.Context) (*Anime, error)
	predicates        []predicate.Anime
}

var _ ent.Mutation = (*AnimeMutation)(nil)

// animeOption allows management of the mutation configuration using functional options.
type animeOption func(*AnimeMutation)

// newAnimeMutation creates new mutation for the Anime entity.
func newAnimeMutation(c config, op Op, opts ...animeOption) *AnimeMutation {
	m := &AnimeMutation{
		config:        c,
		op:            op,
		typ:           TypeAnime,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAnimeID sets the ID field of the mutation.
func withAnimeID(id int64) animeOption {
	return func(m *AnimeMutation) {
		var (
			err   error
			once  sync.Once
			value *Anime
		)
		m.oldValue = func(ctx context.Context) (*Anime, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Anime.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAnime sets the old Anime of the mutation.
func withAnime(node *Anime) animeOption {
	return func(m *AnimeMutation) {
		m.oldValue = func(context.Context) (*Anime, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AnimeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AnimeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Anime entities.
func (m *AnimeMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AnimeMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AnimeMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Anime.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetAverageRating sets the "average_rating" field.
func (m *AnimeMutation) SetAverageRating(f float64) {
	m.average_rating = &f
	m.addaverage_rating = nil
}

// AverageRating returns the value of the "average_rating" field in the mutation.
func (m *AnimeMutation) AverageRating() (r float64, exists bool) {
	v := m.average_rating
	if v == nil {
		return
	}
	return *v, true
}

// OldAverageRating returns the old "average_rating" field's value of the Anime entity.
// If the Anime object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AnimeMutation) OldAverageRating(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAverageRating is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAverageRating requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAverageRating: %w", err)
	}
	return oldValue.AverageRating, nil
}

// AddAverageRating adds f to the "average_rating" field.
func (m *AnimeMutation) AddAverageRating(f float64) {
	if m.addaverage_rating != nil {
		*m.addaverage_rating += f
	} else {
		m.addaverage_rating = &f
	}
}

// AddedAverageRating returns the value that was added to the "average_rating" field in this mutation.
func (m *AnimeMutation) AddedAverageRating() (r float64, exists bool) {
	v := m.addaverage_rating
	if v == nil {
		return
	}
	return *v, true
}

// ResetAverageRating resets all changes to the "average_rating" field.
func (m *AnimeMutation) ResetAverageRating() {
	m.average_rating = nil
	m.addaverage_rating = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *AnimeMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *AnimeMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Anime entity.
// If the Anime object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AnimeMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *AnimeMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the AnimeMutation builder.
func (m *AnimeMutation) Where(ps ...predicate.Anime) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AnimeMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AnimeMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Anime, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AnimeMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AnimeMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Anime).
func (m *AnimeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AnimeMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.average_rating != nil {
		fields = append(fields, anime.FieldAverageRating)
	}
	if m.updated_at != nil {
		fields = append(fields, anime.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AnimeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case anime.FieldAverageRating:
		return m.AverageRating()
	case anime.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AnimeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case anime.FieldAverageRating:
		return m.OldAverageRating(ctx)
	case anime.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Anime field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AnimeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case anime.FieldAverageRating:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAverageRating(v)
		return nil
	case anime.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Anime field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AnimeMutation) AddedFields() []string {
	var fields []string
	if m.addaverage_rating != nil {
		fields = append(fields, anime.FieldAverageRating)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AnimeMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case anime.FieldAverageRating:
		return m.AddedAverageRating()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AnimeMutation) AddField(name string, value ent.Value) error {
	switch name {
	case anime.FieldAverageRating:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAverageRating(v)
		return nil
	}
	return fmt.Errorf("unknown Anime numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AnimeMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AnimeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AnimeMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Anime nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AnimeMutation) ResetField(name string) error {
	switch name {
	case anime.FieldAverageRating:
		m.ResetAverageRating()
		return nil
	case anime.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Anime field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AnimeMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AnimeMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AnimeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AnimeMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AnimeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AnimeMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AnimeMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Anime unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AnimeMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Anime edge %s", name)
}

// UserRatingMutation represents an operation that mutates the UserRating nodes in the graph.
type UserRatingMutation struct {
	config
	op            Op
	typ           string
	id            *int64
	user_id       *int64
	adduser_id    *int64
	anime_id      *int64
	addanime_id   *int64
	rating        *float64
	addrating     *float64
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*UserRating, error)
	predicates    []predicate.UserRating
}

var _ ent.Mutation = (*UserRatingMutation)(nil)

// userratingOption allows management of the mutation configuration using functional options.
type userratingOption func(*UserRatingMutation)

// newUserRatingMutation creates new mutation for the UserRating entity.
func newUserRatingMutation(c config, op Op, opts ...userratingOption) *UserRatingMutation {
	m := &UserRatingMutation{
		config:        c,
		op:            op,
		typ:           TypeUserRating,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserRatingID sets the ID field of the mutation.
func withUserRatingID(id int64) userratingOption {
	return func(m *UserRatingMutation) {
		var (
			err   error
			once  sync.Once
			value *UserRating
		)
		m.oldValue = func(ctx context.Context) (*UserRating, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().UserRating.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUserRating sets the old UserRating of the mutation.
func withUserRating(node *UserRating) userratingOption {
	return func(m *UserRatingMutation) {
		m.oldValue = func(context.Context) (*UserRating, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserRatingMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserRatingMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of UserRating entities.
func (m *UserRatingMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserRatingMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserRatingMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().UserRating.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUserID sets the "user_id" field.
func (m *UserRatingMutation) SetUserID(i int64) {
	m.user_id = &i
	m.adduser_id = nil
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *UserRatingMutation) UserID() (r int64, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the UserRating entity.
// If the UserRating object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserRatingMutation) OldUserID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// AddUserID adds i to the "user_id" field.
func (m *UserRatingMutation) AddUserID(i int64) {
	if m.adduser_id != nil {
		*m.adduser_id += i
	} else {
		m.adduser_id = &i
	}
}

// AddedUserID returns the value that was added to the "user_id" field in this mutation.
func (m *UserRatingMutation) AddedUserID() (r int64, exists bool) {
	v := m.adduser_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetUserID resets all changes to the "user_id" field.
func (m *UserRatingMutation) ResetUserID() {
	m.user_id = nil
	m.adduser_id = nil
}

// SetAnimeID sets the "anime_id" field.
func (m *UserRatingMutation) SetAnimeID(i int64) {
	m.anime_id = &i
	m.addanime_id = nil
}

// AnimeID returns the value of the "anime_id" field in the mutation.
func (m *UserRatingMutation) AnimeID() (r int64, exists bool) {
	v := m.anime_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAnimeID returns the old "anime_id" field's value of the UserRating entity.
// If the UserRating object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserRatingMutation) OldAnimeID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAnimeID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAnimeID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAnimeID: %w", err)
	}
	return oldValue.AnimeID, nil
}

// AddAnimeID adds i to the "anime_id" field.
func (m *UserRatingMutation) AddAnimeID(i int64) {
	if m.addanime_id != nil {
		*m.addanime_id += i
	} else {
		m.addanime_id = &i
	}
}

// AddedAnimeID returns the value that was added to the "anime_id" field in this mutation.
func (m *UserRatingMutation) AddedAnimeID() (r int64, exists bool) {
	v := m.addanime_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetAnimeID resets all changes to the "anime_id" field.
func (m *UserRatingMutation) ResetAnimeID() {
	m.anime_id = nil
	m.addanime_id = nil
}

// SetRating sets the "rating" field.
func (m *UserRatingMutation) SetRating(f float64) {
	m.rating = &f
	m.addrating = nil
}

// Rating returns the value of the "rating" field in the mutation.
func (m *UserRatingMutation) Rating() (r float64, exists bool) {
	v := m.rating
	if v == nil {
		return
	}
	return *v, true
}

// OldRating returns the old "rating" field's value of the UserRating entity.
// If the UserRating object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserRatingMutation) OldRating(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRating is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRating requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRating: %w", err)
	}
	return oldValue.Rating, nil
}

// AddRating adds f to the "rating" field.
func (m *UserRatingMutation) AddRating(f float64) {
	if m.addrating != nil {
		*m.addrating += f
	} else {
		m.addrating = &f
	}
}

// AddedRating returns the value that was added to the "rating" field in this mutation.
func (m *UserRatingMutation) AddedRating() (r float64, exists bool) {
	v := m.addrating
	if v == nil {
		return
	}
	return *v, true
}

// ResetRating resets all changes to the "rating" field.
func (m *UserRatingMutation) ResetRating() {
	m.rating = nil
	m.addrating = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *UserRatingMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *UserRatingMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the UserRating entity.
// If the UserRating object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserRatingMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *UserRatingMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *UserRatingMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *UserRatingMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the UserRating entity.
// If the UserRating object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserRatingMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *UserRatingMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the UserRatingMutation builder.
func (m *UserRatingMutation) Where(ps ...predicate.UserRating) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserRatingMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserRatingMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.UserRating, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserRatingMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserRatingMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (UserRating).
func (m *UserRatingMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserRatingMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.user_id != nil {
		fields = append(fields, userrating.FieldUserID)
	}
	if m.anime_id != nil {
		fields = append(fields, userrating.FieldAnimeID)
	}
	if m.rating != nil {
		fields = append(fields, userrating.FieldRating)
	}
	if m.created_at != nil {
		fields = append(fields, userrating.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, userrating.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserRatingMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case userrating.FieldUserID:
		return m.UserID()
	case userrating.FieldAnimeID:
		return m.AnimeID()
	case userrating.FieldRating:
		return m.Rating()
	case userrating.FieldCreatedAt:
		return m.CreatedAt()
	case userrating.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserRatingMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case userrating.FieldUserID:
		return m.OldUserID(ctx)
	case userrating.FieldAnimeID:
		return m.OldAnimeID(ctx)
	case userrating.FieldRating:
		return m.OldRating(ctx)
	case userrating.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case userrating.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown UserRating field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserRatingMutation) SetField(name string, value ent.Value) error {
	switch name {
	case userrating.FieldUserID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case userrating.FieldAnimeID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAnimeID(v)
		return nil
	case userrating.FieldRating:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRating(v)
		return nil
	case userrating.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case userrating.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown UserRating field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserRatingMutation) AddedFields() []string {
	var fields []string
	if m.adduser_id != nil {
		fields = append(fields, userrating.FieldUserID)
	}
	if m.addanime_id != nil {
		fields = append(fields, userrating.FieldAnimeID)
	}
	if m.addrating != nil {
		fields = append(fields, userrating.FieldRating)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserRatingMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case userrating.FieldUserID:
		return m.AddedUserID()
	case userrating.FieldAnimeID:
		return m.AddedAnimeID()
	case userrating.FieldRating:
		return m.AddedRating()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserRatingMutation) AddField(name string, value ent.Value) error {
	switch name {
	case userrating.FieldUserID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUserID(v)
		return nil
	case userrating.FieldAnimeID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAnimeID(v)
		return nil
	case userrating.FieldRating:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRating(v)
		return nil
	}
	return fmt.Errorf("unknown UserRating numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserRatingMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserRatingMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserRatingMutation) ClearField(name string) error {
	return fmt.Errorf("unknown UserRating nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserRatingMutation) ResetField(name string) error {
	switch name {
	case userrating.FieldUserID:
		m.ResetUserID()
		return nil
	case userrating.FieldAnimeID:
		m.ResetAnimeID()
		return nil
	case userrating.FieldRating:
		m.ResetRating()
		return nil
	case userrating.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case userrating.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown UserRating field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserRatingMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserRatingMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserRatingMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserRatingMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserRatingMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserRatingMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserRatingMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown UserRating unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserRatingMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown UserRating edge %s", name)
}
