// Code generated by ent, DO NOT EDIT.

package anime

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the anime type in the database.
	Label = "anime"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAverageRating holds the string denoting the average_rating field in the database.
	FieldAverageRating = "average_rating"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the anime in the database.
	Table = "anime"
)

// Columns holds all SQL columns for anime fields.
var Columns = []string{
	FieldID,
	FieldAverageRating,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAverageRating holds the default value on creation for the "average_rating" field.
	DefaultAverageRating float64
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Anime queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAverageRating orders the results by the average_rating field.
func ByAverageRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAverageRating, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
