// Code generated by ent, DO NOT EDIT.

package anime

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/seva/animevista/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Anime {
	return predicate.Anime(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Anime {
	return predicate.Anime(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Anime {
	return predicate.Anime(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Anime {
	return predicate.Anime(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Anime {
	return predicate.Anime(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Anime {
	return predicate.Anime(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Anime {
	return predicate.Anime(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Anime {
	return predicate.Anime(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Anime {
	return predicate.Anime(sql.FieldLTE(FieldID, id))
}

// AverageRating applies equality check predicate on the "average_rating" field. It's identical to AverageRatingEQ.
func AverageRating(v float64) predicate.Anime {
	return predicate.Anime(sql.FieldEQ(FieldAverageRating, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Anime {
	return predicate.Anime(sql.FieldEQ(FieldUpdatedAt, v))
}

// AverageRatingEQ applies the EQ predicate on the "average_rating" field.
func AverageRatingEQ(v float64) predicate.Anime {
	return predicate.Anime(sql.FieldEQ(FieldAverageRating, v))
}

// AverageRatingNEQ applies the NEQ predicate on the "average_rating" field.
func AverageRatingNEQ(v float64) predicate.Anime {
	return predicate.Anime(sql.FieldNEQ(FieldAverageRating, v))
}

// AverageRatingIn applies the In predicate on the "average_rating" field.
func AverageRatingIn(vs ...float64) predicate.Anime {
	return predicate.Anime(sql.FieldIn(FieldAverageRating, vs...))
}

// AverageRatingNotIn applies the NotIn predicate on the "average_rating" field.
func AverageRatingNotIn(vs ...float64) predicate.Anime {
	return predicate.Anime(sql.FieldNotIn(FieldAverageRating, vs...))
}

// AverageRatingGT applies the GT predicate on the "average_rating" field.
func AverageRatingGT(v float64) predicate.Anime {
	return predicate.Anime(sql.FieldGT(FieldAverageRating, v))
}

// AverageRatingGTE applies the GTE predicate on the "average_rating" field.
func AverageRatingGTE(v float64) predicate.Anime {
	return predicate.Anime(sql.FieldGTE(FieldAverageRating, v))
}

// AverageRatingLT applies the LT predicate on the "average_rating" field.
func AverageRatingLT(v float64) predicate.Anime {
	return predicate.Anime(sql.FieldLT(FieldAverageRating, v))
}

// AverageRatingLTE applies the LTE predicate on the "average_rating" field.
func AverageRatingLTE(v float64) predicate.Anime {
	return predicate.Anime(sql.FieldLTE(FieldAverageRating, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Anime {
	return predicate.Anime(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Anime {
	return predicate.Anime(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Anime {
	return predicate.Anime(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Anime {
	return predicate.Anime(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Anime {
	return predicate.Anime(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Anime {
	return predicate.Anime(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Anime {
	return predicate.Anime(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Anime {
	return predicate.Anime(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Anime) predicate.Anime {
	return predicate.Anime(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Anime) predicate.Anime {
	return predicate.Anime(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Anime) predicate.Anime {
	return predicate.Anime(sql.NotPredicates(p))
}
