// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AnimeColumns holds the columns for the "anime" table.
	AnimeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "average_rating", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "numeric(3,1)"}},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AnimeTable holds the schema information for the "anime" table.
	AnimeTable = &schema.Table{
		Name:       "anime",
		Columns:    AnimeColumns,
		PrimaryKey: []*schema.Column{AnimeColumns[0]},
	}
	// UserRatingsColumns holds the columns for the "user_ratings" table.
	UserRatingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "anime_id", Type: field.TypeInt64},
		{Name: "rating", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric(3,1)"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserRatingsTable holds the schema information for the "user_ratings" table.
	UserRatingsTable = &schema.Table{
		Name:       "user_ratings",
		Columns:    UserRatingsColumns,
		PrimaryKey: []*schema.Column{UserRatingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "userrating_user_id_anime_id",
				Unique:  true,
				Columns: []*schema.Column{UserRatingsColumns[1], UserRatingsColumns[2]},
			},
			{
				Name:    "userrating_anime_id",
				Unique:  false,
				Columns: []*schema.Column{UserRatingsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AnimeTable,
		UserRatingsTable,
	}
)

func init() {
	AnimeTable.Annotation = &entsql.Annotation{
		Table: "anime",
	}
	UserRatingsTable.Annotation = &entsql.Annotation{
		Table: "user_ratings",
	}
}
